/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capaPresentacio;

/**
 *
 * @author Familia
 */
public class BaseUI extends javax.swing.JFrame {

    private CtrlPresentacio p;
    String name = "popeye";

    /**
     * Creates new form BaseUI
     */
    public BaseUI() {
        initComponents();
    }

    public BaseUI(CtrlPresentacio p) {
        this.p = p;
        initComponents();
    }

    public void view() {
        log = new LoginUI(this);
        jScrollPane1.setViewportView(log);
        this.revalidate();
        this.setVisible(true);

    }

    public CtrlPresentacio getP() {
        return p;
    }

    public void setP(CtrlPresentacio p) {
        this.p = p;
    }

    public void changeLog() {
        
        log = new LoginUI(this);
        jScrollPane1.setViewportView(log);
    }

    public void changeProblem() {
        psui = new ProblemSelectUI(this);
        psui.setname(name);

        jScrollPane1.setViewportView(psui);
    }

    void close() {
        System.exit(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(520, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private LoginUI log;
    private ProblemSelectUI psui;

}
